### ISSUE TITLE
[FEATURE REQUEST] Surveys

### ISSUE THREAD

**Issue by NotHazed** [billsonnn/nitro-react#130] opened 2023-01-08 15:08 UTC
Do you plan to add this survey form to Nitro?

![image](https://user-images.githubusercontent.com/22569203/211203721-69045975-93d7-4501-b69c-fc7714e5f8d0.png)

**Comment by dank074** [comment] 2023-01-08 23:39
There's a branch dedicated towards it, but we haven't continued to work on it since.

**Comment by dank074** [comment] 2023-01-08 23:42
duplicate of https://github.com/billsonnn/nitro-react/issues/26

**Closed by dank074** 2023-01-08 23:42 UTC
